#------------------------------------------------------------------------------
# AUTHOR: Mart van der Molen
# PLEASE READ THE README.md FILE FOR INSTRUCTIONS
#
#  GLOBAL SETTINGS:
#------------------------------------------------------------------------------
app:
   name: trainAPI
   language: en # Choose between (en & nl)
   version: 1.0.0 # PLEASE DONT CHANGE THIS
   maintenance-mode: false
   storage:
      use-mysql: false # If false the application uses a local file system (JSON)
 # Customize your app with the following settings
   customization:
      theme-color: FFFFFF
#----------------------------------------------------------------------------
#  Discord bot settings
#----------------------------------------------------------------------------
   discord:
        token:  # Your discord bot token
        maintainers: # Discord id's of maintainers
            - 287598871373283329
        presence:
            show-last-station: false # If set to true: presence text will change when a user requests information about station.
            ## ^^^ Please note that this will affect the performance
            default-message: "TrainAPI"
            default-type: PLAYING #PLAYING, LISTENING, WATCHING, STREAMING

#------------------------------------------------------------------------------
# Database
# ONLY SUPPORTS MYSQL
#------------------------------------------------------------------------------
# Please note that "use-mysql" must be set to true in the "app" section above, else this section will be ignored.
#------------------------------------------------------------------------------
database:
  host: localhost
  port: 3306
  user: root
  password: root
  database: trainapi

#------------------------------------------------------------------------------
# All api credentials
#------------------------------------------------------------------------------
api:
  refresh-interval: 3 #In minutes
  # ^^^ 3 minutes IS RECOMMENDED, TO MUCH MAY AFFECT THE PERFORMANCE ALSO YOU CAN BE RATE LIMITED BY NS
  ns-primary-key: SECRETKEY #PRIMARY KEY

